backend:
  name: git-gateway
  branch: master

media_folder: src/img
public_folder: /img

collections:
  - name: "themes"
    label: "Tematiche"
    folder: "src/pages/tematiche"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "theme-page"}
      - {label: "Posizione", name: "orderIndex", widget: "number", default: 1, valueType: "int", min: 1}
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Sottotitolo", name: "subtitle", widget: "string", required: false}
      - {label: "Immagine iniziale", name: "intro_image", widget: "custompathimage", customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/tommasomarchionni/gatsby-fiorucci-franco-netlify-cms/master/src/img/"}
      - {label: "Opere", name: "works", widget: "list", fields: [{label: "Titolo", name: "title", widget: "string"}, {label: "Descrizione", name: "description", widget: "markdown", required: false}, {label: "Immagine", name: "image", required: true, widget: "custompathimage", customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/tommasomarchionni/gatsby-fiorucci-franco-netlify-cms/master/src/img/"}]}

  - name: "pages"
    label: "Pagine"
    folder: "src/pages/pagine"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "generic-page"}
      - {label: "Posizione", name: "orderIndex", widget: "number", default: 1, valueType: "int", min: 1}
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Corpo", name: "body", widget: "markdown"}
      - {label: "Immagine iniziale", name: "intro_image", widget: "custompathimage", customMediaPath: "../../img/", rawMediaPath: "https://raw.githubusercontent.com/tommasomarchionni/gatsby-fiorucci-franco-netlify-cms/master/src/img/"}

  - name: "settings"
    label: "Impostazioni"
    files:
      - file: "src/pages/contatti/index.md"
        label: "Contatti"
        name: "contacts"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Telefono", name: "telephone", widget: "string"}
          - {label: "Indirizzo", name: "address", widget: "text"}

      - file: "src/pages/thanks/index.md"
        label: "Pagina ringraziamento contatti"
        name: "thankyou"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "thankyou-page"}
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Corpo", name: "body", widget: "markdown"}

      - file: "src/pages/not-found/index.md"
        label: "Pagina non trovata"
        name: "notfound"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "notfound-page"}
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Corpo", name: "body", widget: "markdown"}